name = "Simulation73Plotting"
uuid = "2846d769-be22-4083-a76c-fdabc4869842"
authors = ["Graham Smith <grahams@uchicago.edu>"]
version = "0.2.0"

[deps]
AxisIndices = "f52c9ee2-1b1c-4fd8-8546-6350938c7f11"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Simulation73 = "310cc8c8-1ffe-11e9-399c-c5a008d6bdcc"
