name = "Simulation73Plotting"
uuid = "2846d769-be22-4083-a76c-fdabc4869842"
authors = ["Graham Smith <grahams@uchicago.edu>"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
AxisIndices = "f52c9ee2-1b1c-4fd8-8546-6350938c7f11"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieLayout = "5a521ce4-ebb9-4793-b5b7-b334dfe8393c"
Simulation73 = "310cc8c8-1ffe-11e9-399c-c5a008d6bdcc"
